input {
    mongodb {
        uri => 'mongodb://172.17.0.6:27017/admin?ssl=false'
        placeholder_db_dir => '/opt/logstash-mongodb/'
        placeholder_db_name => 'admin_sqlite.db'
        collection => 'users'
        batch_size => 50
    }
}
filter {
}
output {
    elasticsearch {
        action => "index"
        index => "mongo_log_data"
        hosts => ["0.0.0.0:9200"]
    }
    stdout {
        codec => rubydebug
    }
}